### PR TITLE
Adding scramble to the animations

### PR DESCRIPTION
**Pull request by sledigabel**
This animation scrambles all words (separated by any non alphanumerical character).
The mix is giving an impression of blur.

Addresses #22

### CODE REVIEW

**Comment by sledigabel** [comment]
@Eandrju WDYT of this PR? Anything you'd like changed?
Happy to make it an external animation if you don't like it :-)

**Comment by Eandrju** [comment]
Sorry that took half a year. A bit intense period of my life

**Comment by sledigabel** [comment]
No problem at all, thanks for merging!

**Comment by Eandrju** [comment]
interesting idea for the animation, looks like virus from the 90s

**Pull request merged**
